### ISSUE TITLE
(Possible) issue with KSP 1.2 / CC 1.22.2

### ISSUE THREAD

**Issue by ZoeBijl** [pap1723/HistoricalProgression#1]
Gemini 7 / 6A mission gives me issues. After launching Gemini 7 (and circularisation) the orbit param isn’t ticked. This causes the timer to not start ticking either. The orbit param does change when you switch to KSC and back to the vessel.

I’ve a save game with this issue if that’s any help.

KSP: 1.2.2 (Unix) - Unity: 5.4.0p4 - OS: Mac OS X 10.12.1

Mod list:
B9 Part Switch - 1.5.3
Camera Focus Changer - 1.0.1
Chatterer - 0.9.91.1586
Color Coded Canisters - 1.5.1
Community Category Kit - 1.2.1
Community Resource Pack - 0.6.4
Contract Configurator - 1.22.2
Contract Pack: Historical Progression - 1.3
Contract Pack: Bases and Stations - 3.5
Contract Pack: RemoteTech - 2.1.3
Contract Pack: Unmanned Contracts - 0.3.27
DMagic Orbital Science - 1.3.0.7
Fuel Tanks Plus - 1.11
Historical Progression Tech Tree - 1.8
Interstellar Fuel Switch - 2.3
KSP-AVC Plugin - 1.1.6.2
Kerbal Engineer Redux - 1.1.2.8
ModularFlightIntegrator - 1.2.2
Docking Port Alignment Indicator - 6.5.1
NearFutureElectrical - 0.8.2
Final Frontier - 1.2.5.2906
S.A.V.E - 1.4.1.2315
Outer Planets Mod - 2.0
Pilot Assistant - 1.13.2
RLA_Continued - 14.0.1
RealChute - 1.4.1.2
RealPlume - Stock - 0.11.1
RemoteTech - 1.8.3
StationPartsExpansion - 0.4.2
TAC Life Support - 0.12.7
Trajectories - 1.6.5
Kerbal Alarm Clock - 3.8.3
Transfer Window Planner - 1.6

**Comment by ZoeBijl** [comment]
Gemini 5 (Gemini5Orbit) uses:

```
minPeA = @targetBody.AtmosphereAltitude()
```

Where Gemini 7 (Gemini7Orbit) uses:

```
minAltitude = @targetBody.AtmosphereAltitude()
```

Changing this doesn’t seem to matter (tried in game).

**Comment by pap1723** [comment]
This should be fixed as well.

**Comment by ZoeBijl** [comment]
Confirmed fixed.
