### ISSUE TITLE
Gemini 7 / 6A orbit duration seems off

### ISSUE THREAD

**Issue by ZoeBijl** [pap1723/HistoricalProgression#2]
<img width="650" alt="Mission description says 14 days. Mission parameter says 10 days." src="https://cloud.githubusercontent.com/assets/5457769/21412756/8250b7b2-c7ea-11e6-97ef-c9c815b92ff2.png">

From ProjectGemini.cfg:

```
DATA
  {
    type = double
    dayLength = @targetBody.RotationalPeriod()
    tenDays = @dayLength * 10
    title = 10 Days
  }
```

**Comment by pap1723** [comment]
I changed the wording on this. The Gemini 7 mission was 14 days long, but they rendezvoused with Gemini 6 after 10 days. Using CC, there is not a great way to then add 4 more days for the Gemini 7 mission, so I have limited it to simply having a 10 day mission.
