### ISSUE TITLE
Apollo 15 issue with visiting locations

### ISSUE THREAD

**Issue by ZoeBijl** [pap1723/HistoricalProgression#3]
I did this mission with a rocket consisting of three parts—SM, LM, Rover—successfully going through all the motions as set in the params. After I landed (about 2 KM from the designated spot) I decoupled my rover and set off to the various locations. Visiting the landing site gave me a green tick for that param, so that was fine. After visiting location Beta and Charlie I drove back to my lander. Switched Valentina from the rover to the LM and did a final check on the contract.

And there was the problem, all ticks for the locations were gone. I have a save file, craft file, and list of mods to help out here. I’ll manually mark this one as done, but hope this can be solved in a future update :).

**Comment by ZoeBijl** [comment]
Here are three screenshots depicting the design, if that helps at all.

![Service module, lander, and rover flying over the mun](https://cloud.githubusercontent.com/assets/5457769/22180370/463bb3aa-e066-11e6-8aff-fb6e15c13329.png)
![Lander with rover attached flying over the mun](https://cloud.githubusercontent.com/assets/5457769/22180373/4eb39480-e066-11e6-8b2f-bee473165973.png)
![Rover driving toward to the lander on the mun](https://cloud.githubusercontent.com/assets/5457769/22180376/6df059f0-e066-11e6-91b8-9ac6f0c46f84.png)

**Comment by pap1723** [comment]
This is fixed for the next release version.
